[build]
  command = "CI=false npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.2.3"
  CI = "false"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"